kind: Namespace
apiVersion: v1
metadata:
  name: empty-class-ns
  labels:
    name: empty-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-2022
  namespace: empty-class-ns
  labels:
    app: iis-2022
spec:
  replicas: 1
  template:
    metadata:
      name: iis-2022
      labels:
        app: iis-2022
    spec:
      containers:
      - name: iis
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022
        resources:
          limits:
            cpu: 1
            memory: 800Mi
          requests:
            cpu: .1
            memory: 300Mi
        ports:
          - containerPort: 80
        volumeMounts:
        - name: empty-class
          mountPath: C:\inetpub\wwwroot
      nodeSelector:
        common2022: "yes"
      volumes:
       - name: empty-class
         persistentVolumeClaim:
           claimName: empty-class-claim
  selector:
    matchLabels:
      app: iis-2022
---
apiVersion: v1
kind: Service
metadata:
  name: iis
  namespace: empty-class-ns
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iis-2022
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: empty-class
  namespace: empty-class-ns
  labels:
    usage: empty-class
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretNamespace: empty-class-ns
    secretName: azure-secret
    shareName: common00
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: empty-class-claim
  namespace: empty-class-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: empty-class
